on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ACTIONS_STEP_DEBUG: "true"

jobs:
  hash_for_cache:
    name: hash_for_cache

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - id: foo
        uses: KEINOS/gh-action-hash-for-cache@main
        with:
          path: |
            ./testdata/sample1.txt

      - run: |
          expect="92124a1e7e9c5ee0e35c156cff911e56:d41d8cd98f00b204"
          [[ "${expect}" == "${{ steps.foo.outputs.hash }}" ]]
        shell: bash
