on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ACTIONS_STEP_DEBUG: "true"

jobs:
  hash_for_cache:
    name: hash_for_cache

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - id: foo
        uses: KEINOS/gh-action-hash-for-cache@v1.2.0
        with:
          path: |
            ./testdata/sample1.txt

      - run: |
          expect="59dd465085e45174d1a9e0b41eeb4ee1:cf83e1357eefb8bd"
          [[ "${expect}" == "${{ steps.foo.outputs.hash }}" ]]
        shell: bash
